name: MiniWiki CI

on:
    push:
      branches: [deployment]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Run web application
        run: RUNNER_TRACKING_ID="" &&  make run >> ~/log.txt &